######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 19 11:20:35 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
RC_FILE = myapp.rc
QT +=network
HEADERS += gui.h websis.h
SOURCES += gui.cpp main.cpp websis.cpp

RESOURCES += \
    pics.qrc
